app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib import admin

# from django.conf.urls.static import static
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('decrees/', include('decrees.urls')),
    path('admin/', admin.site.urls),
]

# serve static and media files from development server
# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.?MEDIA_ROOT)

decrees/urls.py
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from decrees import appointment_views 

app_name = 'decrees'

urlpatterns = [

    path('login/', appointment_views.MyLogin.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='decrees:login'), name='logout'),

#     path('events/login', appointment_views.MyLogin.as_view(), name='event-login'),

    path('event-form/', appointment_views.EventView.as_view(), name='event-form'),
    path('event-form/create', appointment_views.AddEvent.as_view(), name='create-event'),
    
    path('event-form/<int:pk>', appointment_views.ShowOneEvent.as_view(), name='show-event'),
    
    # path('event-form/update/<int:pk>', appointment_views.EditEvent.as_view(), name='update-event'),
    re_path(r'^event-form/update/(?P<pk>[0-9]{1,999})/*', appointment_views.EditEvent.as_view(), name='update-event'),
    
    path('event-form/<int:pk>/delete', appointment_views.DeleteEvent.as_view(), name='delete-event'),

    path('events/', appointment_views.ShowAllEvents.as_view(), name='show-all-events'),
    path('events/<str:query>', appointment_views.ShowAllEvents.as_view(), name='show-all-events'),



]

# handler404 = decrees.views.error_404

# from django.conf.urls.static import static
# TODO# urlpatterns += static(settings.STAT)

decrees/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from decrees.managers import UserManager

from datetime import datetime
# from django.contrib.auth import get_user_model
# User = get_user_model()

import datetime
# Create your models here.


class MyUser(AbstractUser):
    """
        ('password', models.CharField(max_length=128, verbose_name='password')),
        ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
        ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
        ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
        ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
        ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
        ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
        ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
        ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
        ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),

    """
    location = models.CharField(max_length=201, unique=False, default='default_location')
    # objects = UserManager()

    def get_location(self):
        return f'{self.get_username()} is located at {self.location_2}'
    


class Position(models.Model):
    name = models.CharField(max_length=800)    
    level_choices = [('federal', 'federal'),
                        ('regional','regional')]    

    level = models.CharField(max_length=50, choices=level_choices)

    def __str__(self) -> str:
        return f'{self.name}'


class Person(models.Model):
    name = models.CharField(max_length=300)

    def __str__(self) -> str:
        return self.name


class Event(models.Model): 
    
    class Meta:

        constraints = [
            models.UniqueConstraint(fields=['person','region','position', 'date'], name='unique_event'),
            
        ]

    person = models.ForeignKey(Person, on_delete=models.RESTRICT)
    event_choices = [('appoint', 'appoint'),
                        ('resign','resign')]    
    level_choices = [('federal', 'federal'),
                        ('regional','regional')]

    action = models.CharField(max_length=50, choices=event_choices)
    date = models.DateField()
    position = models.ForeignKey(Position, on_delete=models.RESTRICT)
    level = models.CharField(max_length=51, choices=level_choices)
    full_text = models.CharField(max_length=99999, null=True)
    line = models.CharField(max_length=8000, null=True)
    link = models.CharField(max_length=2000, null=True, default='https://example.com')
    file_name = models.CharField(max_length=599, null=True, default='defaults_file_name')

    region_choices = ['Белгородская область', 'Брянская область', 'Владимирская область', 'Воронежская область', 'Ивановская область', 'Калужская область', 'Костромская область', 'Курская область', 'Липецкая область', 'Московская область', 'Орловская область', 'Рязанская область', 'Смоленская область', 'Тамбовская область', 'Тверская область', 'Тульская область', 'Ярославская область', 'Москва', 'Республика Карелия', 'Республика Коми', 'Архангельская область', 'Ненецкий автономный округ', 'Вологодская область', 'Калининградская область', 'Ленинградская область', 'Мурманская область', 'Новгородская область', 'Санкт-Петербург', 'Республика Адыгея', 'Республика Калмыкия', 'Республика Крым', 'Краснодарский край', 'Астраханская область', 'Волгоградская область', 'Ростовская область', 'Севастополь', 'Республика Башкортостан', 'Республика Марий Эл', 'Республика Мордовия', 'Республика Татарстан', 'Удмуртская Республика', 'Чувашская Республика', 'Кировская область', 'Нижегородская область', 'Оренбургская область', 'Пензенская область', 'Пермский край', 'Самарская область', 'Саратовская область', 'Ульяновская область', 'Курганская область', 'Свердловская область', 'Тюменская область', 'Челябинская область', 'Ханты-Мансийский автономный', 'Ямало-Ненецкий автономный округ', 'Республика Алтай', 'Республика Тыва', 'Республика Хакасия', 'Алтайский край', 'Красноярский край', 'Иркутская область', 'Кемеровская область', 'Новосибирская область', 'Омская область', 'Томская область', 'Республика Бурятия', 'Республика Саха (Якутия)', 'Приморский край', 'Хабаровский край', 'Амурская область', 'Камчатский край', 'Магаданская область', 'Сахалинская область', 'Забайкальский край', 'Еврейская автономная область', 'Чукотский автономный округ', 'Республика Дагестан', 'Республика Ингушетия', 'Кабардино-Балкарская Республика', 'Карачаево-Черкесская Республика', 'Республика Северная Осетия - Алания', 'Чеченская республика', 'Ставропольский край']
    region_choices = [(e,e) for e in region_choices]
    region = models.CharField(max_length=100, choices=region_choices, default='регион не указан')

    def __str__(self) -> str:
        return f'{self.action} {self.position} on {self.date}'






'''        constraints = [
            models.UniqueConstraint(
                fields=['user', 'doc_name'], name="unique_user_docname"
            ),
            models.CheckConstraint(check=models.Q(size__lte=95), name='my_size_limit')
        ]
'''    

decrees/views.py
# from django.shortcuts import get_object_or_404, redirect, render
# from django.urls import reverse
# from django.http import Http404
# from django.http import HttpResponse, HttpResponseRedirect
# from django.shortcuts import get_object_or_404
# from django.views.generic.edit import CreateView, UpdateView, DeleteView
# from django.urls import reverse_lazy, reverse


# # from django.contrib.auth import get_user_model
# # User = get_user_model()

# from django.contrib.auth.views import LoginView
# from django.contrib.auth.mixins import LoginRequiredMixin
# # from django.contrib.auth.forms import UserCreationForm
# from django.views.generic import FormView
# from django.contrib.auth import login
# from decrees.forms import CustomUserCreationForm, TestUserForm


# from .models import Formats, Document


# """ООП"""

# from django.views.generic.list import ListView
# from django.views.generic.base import TemplateView, RedirectView
# from django.views.generic.detail import DetailView

# class MyLogin(LoginView):
#     fields = ['__all__'] 
#     template_name = 'converter/log-in-form.html'
#     redirect_authenticated_user = True

#     def get_success_url(self): 
#         return reverse_lazy('converter:show_all_docs')


# class MyRedirect(RedirectView):
    
#     pattern_name = 'converter:show_all_docs'
#     query_string = True

#     def get_redirect_url(self, *args, **kwargs):
#         print('перенаправляем!')
#         # print('kwargs---', kwargs)
#         # kwargs = {'mykwargs': kwargs['arg']}
#         return reverse('converter:show_all_docs')

# class MyTemplateView(TemplateView):
#     template_name = 'converter/template.html'

#     """    
#     в оригинале так:
#     def get(self, request, *args, **kwargs):
#          context = self.get_context_data(**kwargs)
#          return self.render_to_response(context)
    
#     и можно переписать
#     """

#     def get(self, *args, **kwargs):
#         r = locals()['args'][0]
#         return render(r, self.template_name, kwargs)

#     # получить контекст (параметры)
#     # def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:con
#         # return super().get_context_data(**kwargs)


# # def authenticate(r):
# #     from django.contrib.auth import authenticate
# #     user = authenticate(username='john', password='secret')
# #     if user is not None:
# #         pass
# #         # A backend authenticated the credentials
# #     else:
# #         # No backend authenticated the credentials
# #         pass

# # def login_form(r):
# #     # МНЕ НАДО
# #     return render(r, 'converter/log-in-form.html')


# # моя логин форма содержит какой то кал
# '''            {% with messages = get_flashed_messages(with_categories=true) %}

#             {% endwith %}
# '''


# class Created(TemplateView):
#     template_name = 'converter/docs/doc_created.html'
    
#     def get(self, *args, **kwargs):
#         r = locals()['args'][0]
#         return render(r, self.template_name, kwargs)


# class AddDoc(CreateView):
#     template_name = 'converter/docs/doc_created.html'
#     model = Document
#     fields = ['doc_name', 'doc_format', 'size']
#     success_url = reverse_lazy('converter:created')


# class UpdateDoc(UpdateView):
#     context_object_name = 'doc'
#     template_name = 'converter/docs/update_doc.html'
#     model = Document
#     fields = ['doc_name']
#     # fields = '__all__'
#     success_url = reverse_lazy('converter:created')


# class DeleteDoc(DeleteView):
#     context_object_name = 'doc'
#     model = Document
#     template_name = 'converter/docs/cofirm_delete.html'
#     success_url = reverse_lazy('converter:show_all_docs')


# class DocItem(LoginRequiredMixin, DetailView):
#     model = Document
#     template_name = 'converter/docs/show_one_doc.html'


# class DocsList(LoginRequiredMixin, ListView):
#     model = Document
#     template_name = 'converter/docs/show_docs_oop.html'
#     context_object_name = 'docs'
#     paginate = 2

#     def get_queryset(self):
#         user = self.request.user
#         query_format = self.kwargs.get('format')
#         # breakpoint()
#         if not query_format:
#             docs = Document.objects.filter(user=user).order_by('-size')
#         else:
#             format = Formats.objects.filter(formatname=query_format)[0].id 
#             docs = Document.objects.filter(user=user, doc_format=format).order_by('-size')
#         return docs

#     def get_context_data(self, **kwargs):
#         query_format = self.kwargs.get('format')

#         if not query_format:
#             query_format = 'Формат'
        
#         context = super().get_context_data(**kwargs)
#         context.update({
#             'formats_list':Formats.objects.all(),
#             'chosen_format':query_format
#         })
#         return context
    
#     def get(self, *args, **kwargs):
#         query_format = kwargs.get('format')

#         from django.http import Http404
#         if query_format == 'txt':
#             raise Http404('очко')
#         # переадресация с аргументом
#         # if query_format == 'txt':
#         #     return redirect('converter:show_all_docs', 'pdf')
        
#         return super(DocsList, self).get(*args, **kwargs)


#     # можно еще так фильтровать
#     # def get_context_data(self, **kwargs):
#     #     context = super().get_context_data(**kwargs)
#     #     docs = context['docs'].filter(user=self.request.user)
#     #     return docs

# class MyRegisterForm(FormView):
#     template_name = 'converter/register-form.html' 
#     form_class = CustomUserCreationForm
#     success_url = reverse_lazy('converter:show_all_docs')
#     redirect_authenticated_user = True

#     def form_valid(self, form):
#         """If the form is valid, redirect to the supplied URL."""
#         user = form.save()
#         if user is not None:
#             login(self.request, user)
#         return super(MyRegisterForm, self).form_valid(form)

#     def get(self, *args, **kwargs):
#         if self.request.user.is_authenticated:
#             print('перенаправили зареганого юзера')
#             return redirect('converter:show_all_docs')
#         return super(MyRegisterForm, self).get(*args, **kwargs)


# class TestForm(FormView):
#     template_name = 'converter/test_form.html'
#     form_class = TestUserForm
#     success_url = reverse_lazy('converter:show_all_docs')
#     redirect_authenticated_user = True


# """функциональный подход"""

# def error_404(request, exception):
#     return render(request,'converter/404.html', exception)


# def upload_form(r):
#     if r.method ==  'POST':
#         return HttpResponse('отправили файлы))')
#     formats = {"formats": Formats.objects.all()}
#     return render(r, 'converter/show_upload_form.html', formats)


# def test_upload_form(request):
#     print(request)
#     print(request.POST)
#     formats = Formats.objects.all()
#     data = {"formats": formats}
#     # print('data--', data['formats'])

#     # data = {"formats": [{"formatname": e} for e in ['zip', 'rogue']]}

#     return render(request, 'converter/upload_form.html', data)


# def test_redirect(r, format):
#     return HttpResponse(format)
#     # return render(r, 'converter/show_choosen_format.html', data)


# def choose_format(r, choosen_format):
#     all_formats = Formats.objects.all()
#     if not choosen_format:
#         formats_objects = Formats.objects.all()

#     else:
#         formats_objects = Formats.objects.filter(formatname=choosen_format)

#     documents = [e.document_set.all() for e in formats_objects]

#     data = {"formats": formats_objects, 'documents': documents,
#             'choosen_format': choosen_format, 'all_formats': all_formats}

#     return render(r, 'converter/show_docs.html', data)


# def show_choosen_format(r, format):
#     print('show_choosen_format r ::::', r)
#     print('show_choosen_format format ::::', format)

#     # тут чет нет choice в посте

#     choosen_format = r.POST['choice']
#     format = Formats.objects.filter(formatname=choosen_format)
#     # format = get_object_or_404(Formats, formatname=choosen_format)

#     if format:
#         print('format---', format[0])
#         format_docs = format[0].document_set.all()
#         data = {"format": choosen_format, "docs": [
#             e.doc_name for e in format_docs]}

#         # TODO: в html можно обращаться к объектам из БД {{ format.docs_set.all() }}
#         print('data---', data)

#         return render(r, 'converter/show_choosen_format.html', data)
#         # return HttpResponseRedirect(reverse('converter:test_redirect',
#         #                                     kwargs={'format': 'val'}))

#     else:
#         formats = Formats.objects.all()
#         my_error = 'выбран rogue format!'
#         data = {"formats": formats, 'errors': my_error}
#         return render(r, 'converter/upload_form.html', data)


# def test_base(r):
#     return render(r, 'converter/base.html')

decrees/templates/decrees/decrees/all_events.html
{% extends 'decrees/decrees/main.html' %}
{% load static %} 


{% block table %}


{% load my_tags %}
<div class="table_wrapper">
  
  <table class="table table-sm">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Имя</th>
        <th scope="col">Событие</th>
        <th scope="col">Должность</th>
        <th scope="col">Регион</th>
        <th scope="col">Дата</th>
        <th scope="col">Действия</th>
        
    </tr>
    </thead>
    <tbody>


    {% for event in events %}
    <tr>
        <td>{{event.row_number}}.</td>
        <td>{{event.person.name}}</td>
        
        {% if event.action == "appoint" %}
        <td>назначение</td>
        {% endif %}

        {% if event.action == "resign" %}
        <td>отставка</td>
        {% endif %}
        <!-- <td>{{event.action}}</td> -->
        <td>{{event.position|truncatechars:80}}</td>
        <td>{{event.region}}</td>
        <td>{{event.date}}</td>
        <td>
            <div> 
            <a href="{% url 'decrees:update-event' event.pk  %}">Править</a>
        </div>
        <div>
            <a href="{% url 'decrees:show-event' event.pk  %}">Смотреть</a>
        </div>
        
        </td>
        
    </tr>
    {% endfor %}
    </tbody>
    </table>

</div>

{% if not events %}
<h4>таких событий нет</h4>
{% endif %}

<!-- <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            
            <a href="{% my_relative_url 1 'page' request.GET.urlencode %}">first</a>
            <a href="{% my_relative_url page_obj.previous_page_number 'page' request.GET.urlencode %}">previous</a>

            {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="{% my_relative_url page_obj.next_page_number 'page' request.GET.urlencode %}">next</a>
            <a href="{% my_relative_url page_obj.paginator.num_pages 'page' request.GET.urlencode %}">last</a>

        {% endif %}
    </span>
</div> -->



    <script>
        new TomSelect("#select-beast-empty",{
	allowEmptyOption: true,
	create: true
            });

</script>

<script>
    new TomSelect("#input-tags",{
	persist: false,
	createOnBlur: true,
	create: true
});

// new TomSelect("#input-tags-date",{
// 	// persist: false,
// 	// createOnBlur: true,
// 	create: false
// });


</script>

<script>
  new TomSelect("#input-tags-position",{
persist: false,
createOnBlur: true,
create: true
});
</script>
{% if events %}


<div class="pagination">

    <section class="p-4 d-flex justify-content-center mb-4">
      <nav aria-label="Page navigation example">
        <ul class="pagination mb-0">

        {% if page_obj.has_previous %}

        <li>
            {% if page_obj.number > 3 %}
                <a class="page-link" href="{% my_relative_url 1 'page' request.GET.urlencode %}" aria-label="Next">
                    <span aria-hidden="true"> 1 </span>
                    </a>
                </li>
            {% endif %}
    
            <li class="page-item">
            <a class="page-link" href="{% my_relative_url page_obj.previous_page_number 'page' request.GET.urlencode %}" aria-label="Previous">
              <span aria-hidden="true"> < </span>
            </a>
          </li>
          
        <!-- <li class="page-item"><a class="page-link" href="{% my_relative_url page_obj.previous_page_number 'page' request.GET.urlencode %}"> если есть прр{{page_obj.number|add:"-1"}}</a></li> -->


        {% endif %}

        
        {% if page_obj.paginator.page_range|length < 4 %}
          {% for page in page_obj.paginator.page_range %}
                {%  if page == page_obj.number %}
               <b><li   class="page-item"><a class="page-link" href="{% my_relative_url page 'page' request.GET.urlencode %}">{{page}}</a></li></b> 
                {% else %}  
                <li   class="page-item"><a class="page-link" href="{% my_relative_url page 'page' request.GET.urlencode %}">{{page}}</a></li>
 
                {% endif %}
                
            {% endfor %}
        
        {% else %}  
            <!-- ТЕКУЩАЯ СТРАНИЦА -->
          <b>  <li class="page-item" id="current_page"><a  class="page-link" href="#">{{page_obj.number}}</a></li></b>
        
        {% endif %}
        

          {% if page_obj.has_next %}
            <!-- следующая страница -->
            <li class="page-item"><a class="page-link" href="{% my_relative_url page_obj.next_page_number 'page' request.GET.urlencode %}"> > </a></li>
          
                 
                {% if page_obj.number|add:'1' < page_obj.paginator.page_range|length %}

                      <li class="page-item"><a class="page-link" href="{% my_relative_url page_obj.paginator.page_range|length 'page' request.GET.urlencode %}"> {{page_obj.paginator.page_range|length}} </a></li>

                  {% endif %}
          
          {% endif %}

        </ul>

        
      </nav>
    </section>
</div>


{% endif %}

    <script type="text/javascript" src="{% static 'decrees/js/declarator.js' %}"></script>

    

    
  
{% endblock %}

decrees/templates/decrees/decrees/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=], initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

        <link rel="stylesheet" type="text/css" href="{% static 'decrees/css/my_forms.css' %}">

          <!-- jQuery -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

        <!-- Fengyuan Chen's Datepicker -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>

        <!-- --Tom select  --> 
        <script src="https://cdn.jsdelivr.net/npm/tom-select@2.0.2/dist/js/tom-select.complete.min.js"></script>
        <link href="https://cdn.jsdelivr.net/npm/tom-select@2.0.2/dist/css/tom-select.css" rel="stylesheet">

    </head>
<body>
<!-- профиль -->
<!-- <a href=" {% url 'decrees:logout' %} ">лог аут</a> -->
    <br>
{% block main %}
{% endblock %}

{% block card %}
{% endblock %}

{% block login %}
{% endblock %}



<!-- БУТ СТРАП -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
crossorigin="anonymous"></script>

<link rel="stylesheet" type="text/css" href="{% static 'decrees/css/my_forms.css' %}">


</body>

decrees/templates/decrees/decrees/confirm_delete.html
{% extends 'decrees/decrees/main.html' %}

{% block main %}

{{event}}

{% endblock %}

decrees/templates/decrees/decrees/login.html
{% extends 'decrees/decrees/base.html' %}
{% load static %} 

{% block login %}
<br><br><br>
    <div class="row">
        <div class="col">

        </div>
        <div class="col-4 login-form">

                        
            {% if form.errors %}
            <p>Your username and password didn't match. Please try again.</p>
            {% endif %}

            {% if next %}
                {% if user.is_authenticated %}
                <p>Your account doesn't have access to this page. To proceed,
                please login with an account that has access.</p>
                {% else %}
                <p>Please login to see this page.</p>
                {% endif %}
            {% endif %}

            <form method="post" action="{% url 'decrees:login' %}">
            {% csrf_token %}
            <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
            </table>

            <input type="submit" value="login">
            <input type="hidden" name="next" value="{{ next }}">
            </form>

            <!-- <form action="POST" name="login-form">
                {% csrf_token %}
            
                {{form}}
                <button type="submit" class="btn btn-primary">Submit</button>

            </form> -->
    
            <!-- <form method="POST" action="">
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Email address</label>
                    <input type="text" name="user_email" class="form-control" id="exampleInputEmail1">
                </div>

                <div class="mb-3">
                    <label for="exampleInputPassword1" class="form-label">Password</label>
                    <input type="password" name="user_pass" class="form-control" id="exampleInputPassword1">
                </div>
                
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
         -->
        
        </div>
        <div class="col">
            <!-- <p><a href="">Зарегаться</a></p> -->
        </div>
    </div>
        
    {% endblock %}

decrees/templates/decrees/decrees/main.html
{% extends 'decrees/decrees/base.html' %}
{% load static %} 

{% block main %}

<div class="container">
    <div class="row">
      <div class="col col-3 test-col">
        {% block menu %}
        {% endblock %}

      </div>
      <div class="col col-9 test-col">
        {% block table %}
        {% endblock %}

    </div>
      <!-- <div class="col col-4">
       3 Одна из трёх колонок
      </div> -->
    </div>
  </div>



{% endblock %}

decrees/templates/decrees/decrees/temp_pag.html
    {% block pagination %}
    {% for page_number in page_obj.paginator.get_elided_page_range %}
        {% if page_number == page_obj.paginator.ELLIPSIS %}
        <!-- точки -->
        {{page_number}}
  {% else %}
      <a href="{% my_relative_url page_number 'page' request.GET.urlencode %}">
        {{page_number}}
    </a>

        {% endif %}
    {% endfor %}

    {% if page_obj.has_previous %}
        <a href="">
            Previous Page
        </a>
    {% endif%}

    <!-- {% if page_obj.has_next %}
        <a >
            Next Page
        </a>
    {% endif%}

    {% if page_obj.has_previous %}
    <a href="">
        First Page
    </a>
{% endif%} -->

{% if page_obj.has_next %}
    <a href="">
        Last Page
    </a>


{% endif%}

decrees/templates/decrees/decrees/update_event_form.html
{% extends 'decrees/decrees/base.html' %}

{% block card %}

<div class="container" >
  <div class="row">

      <div class="col col-2">

        <a href="javascript:history.back()" id="get_back_link_text">

    <!-- <a  href="{% url 'decrees:show-all-events' %}" id="get_back_link_text"> -->
          
          <div id='get_back_link_wrapper'>
              <div class="get_back_button"> <h3>Назад</h3></div>
          </div>

        </a>

    </div>

  <div class="col col-7" id="card-wrapper">
          <!-- <div class="col col-7"> -->
            <h3>Событие</h3>
            <br>
            <h1></h1>
            <form method="post">

                {% csrf_token %}
                <div class="mb-3">
                    {{form.person}}
                </div>

                <div class="mb-3">
                    {{form.date}}
                </div>

                <div class="mb-3">
                    
                  {{form.action}}

                </div>
                
                <div class="mb-3">
                    <h5>Должность</h5>
                    {{form.position}}
                </div>
               
                <div class="mb-3">
                  <p>
                        <a class="btn btn-secondary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                          Полный текст документа &#9660;
                        </a>

                  </p>

                      <div class="collapse" id="collapseExample">
                        {{form.full_text}}
                        <br>
                          {% if download_link %}
                          <!-- <a href="{{ download_link }}"> <button  class="btn btn-primary">Скачать </button> </a> -->
                        {% endif %}

                        <button id="download_link" class="btn btn-primary"><a id='download_link' href="{{ download_link }}">скачать</a></button>                                                

                      </div>
                </div>

                <button type="submit" class="btn btn-primary">Сохранить изменения </button>
                <!-- <button id="delete_event_button" type="button" class="btn btn-light">Удалить событие</button> -->
                  
            </form>
            <br>
            <br>
            <br>
            
          </div>

          <div class="col col-2"> </div>

        </div>

        </div>


{% endblock %}





    
    <!-- {{form.as_p}} -->
 
      <!-- дейт пикер -->
      <!-- <script>
        $(function () {
          $("#id_date").datepicker({
            format:'dd/mm/yyyy',
          });
        });
      </script> -->